"""
GET /api/tts/audio/{audio_id}

Serves cached MP3 audio generated by the voice service.
Audio entries are stored in-memory with a 10-minute TTL.
"""
from __future__ import annotations

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import Response

from app.dependencies import get_current_user_flexible
from app.models.user import User
from app.services.voice_service import AudioCache

router = APIRouter(tags=["tts"])

# ── Module-level ref, set from main.py ────────────────────────────────────────

_audio_cache: AudioCache | None = None


def init_tts_globals(audio_cache: AudioCache) -> None:
    """Called from main.py to inject the shared AudioCache."""
    global _audio_cache
    _audio_cache = audio_cache


@router.get("/tts/audio/{audio_id}")
async def get_tts_audio(
    audio_id: str,
    user: User = Depends(get_current_user_flexible),
):
    """
    Serve a cached MP3 audio file by its audio_id.

    Requires authentication. Returns 404 if audio_id is expired or unknown.
    """
    if _audio_cache is None:
        raise HTTPException(status_code=503, detail="TTS service not initialized")

    mp3_bytes = _audio_cache.get(audio_id)
    if mp3_bytes is None:
        raise HTTPException(status_code=404, detail="Audio not found or expired")

    return Response(
        content=mp3_bytes,
        media_type="audio/mpeg",
        headers={
            "Cache-Control": "private, max-age=300",
            "Content-Disposition": f'inline; filename="{audio_id}.mp3"',
        },
    )
